In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
from numpy.linalg import eig

In [5]:
file_path ="output_reflectance4.csv"

df = pd.read_csv(file_path)

file_names = df.iloc[:, 0].values

feature_names = df.columns[1:]

data = df.iloc[:, 1:].values

print("File Names:", file_names)
print("Feature Names:", feature_names)
print("Data as NumPy Array:\n", data)


File Names: ['D1GB1.csv' 'D1GB2.csv' 'D1GS1.csv' 'D1GS2.csv' 'D1GS3.csv' 'D1GS4.csv'
 'D1GS5.csv' 'D1GT1.csv' 'D1GT2.csv' 'D1RB1.csv' 'D1RB2.csv' 'D1RS1.csv'
 'D1RS2.csv' 'D1RS3.csv' 'D1RS4.csv' 'D1RS5.csv' 'D1RS6.csv' 'D1RT1.csv'
 'D2GB1.csv' 'D2GS1.csv' 'D2GS2.csv' 'D2GS3.csv' 'D2GS4.csv' 'D2GT1.csv'
 'D2GT2.csv' 'D2RB1.csv' 'D2RS1.csv' 'D2RS2.csv' 'D2RS3.csv' 'D2RS4.csv'
 'D2RS5.csv' 'D2RS6.csv' 'D2RT1.csv' 'D2RT2.csv' 'D3GB1.csv' 'D3GS1.csv'
 'D3GS2.csv' 'D3GS3.csv' 'D3GS4.csv' 'D3GT1.csv' 'D3GT2.csv' 'D3RB1.csv'
 'D3RS1.csv' 'D3RS2.csv' 'D3RS3.csv' 'D3RS4.csv' 'D3RS5.csv' 'D3RT1.csv'
 'D3RT2.csv' 'D4RB1.csv' 'D4RS1.csv' 'D4RS2.csv' 'D4RS3.csv' 'D4RS4.csv'
 'D4RS5.csv' 'D4RT1.csv' 'D4RT2.csv' 'D5GB1.csv' 'D5GS1.csv' 'D5GS2.csv'
 'D5GS3.csv' 'D5GS4.csv' 'D5GT1.csv' 'D5GT2.csv' 'D5RB1.csv' 'D5RS1.csv'
 'D5RS2.csv' 'D5RS3.csv' 'D5RS4.csv' 'D5RS5.csv' 'D5RT1.csv' 'D5RT2.csv'
 'D6GB1.csv' 'D6GS1.csv' 'D6GS2.csv' 'D6GS3.csv' 'D6GT1.csv' 'D6GT2.csv'
 'D6RB1.csv' 'D6RS1.csv' 'D6RS2.csv' 'D

In [6]:
print(df)

    File Name  356.0  366.0  376.0  386.0  396.0  406.0  416.0  426.0  436.0  \
0   D1GB1.csv  28.85  25.03  20.18  16.29  16.25  13.77  13.90  13.66  13.03   
1   D1GB2.csv  29.34  24.67  19.33  15.57  15.60  13.14  13.39  12.97  12.34   
2   D1GS1.csv  34.83  29.01  22.76  17.90  17.87  14.91  15.42  15.65  15.24   
3   D1GS2.csv  36.25  30.23  23.91  19.12  18.83  15.72  16.15  16.27  15.67   
4   D1GS3.csv  32.55  27.56  21.11  16.76  17.63  14.43  14.56  14.12  13.32   
..        ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
81  D6RS3.csv   8.96   7.00   5.62   4.13   4.01   3.02   2.85   2.59   2.33   
82  D6RS4.csv  15.90  13.74  11.90  10.11   9.78   8.56   8.22   7.81   7.52   
83  D6RS5.csv  14.46  12.38   9.81   8.27   7.79   6.39   6.13   5.68   5.29   
84  D6RT1.csv  10.47   9.11   7.27   6.02   5.87   4.72   4.53   4.27   4.11   
85  D6RT2.csv  11.22   9.60   7.71   6.72   6.55   5.35   5.34   4.99   4.83   

    ...  2416.0  2426.0  2436.0  2446.0

In [8]:
numeric_data = df.iloc[:, 1:].values
print(numeric_data)

[[28.85 25.03 20.18 ...  6.71  6.27  6.25]
 [29.34 24.67 19.33 ...  6.86  7.34  6.4 ]
 [34.83 29.01 22.76 ... 10.23 10.4   9.71]
 ...
 [14.46 12.38  9.81 ...  4.78  5.12  3.63]
 [10.47  9.11  7.27 ...  2.57  2.42  2.8 ]
 [11.22  9.6   7.71 ...  4.34  3.78  4.2 ]]


In [9]:
mean_centered_data = numeric_data - np.mean(numeric_data, axis=0)
normalized_data = mean_centered_data / np.std(numeric_data, axis=0)

In [12]:
print(normalized_data)

[[ 1.03443931  1.14778549  1.14140681 ...  0.30936973  0.16280414
   0.23321042]
 [ 1.09863097  1.09344248  0.98898849 ...  0.35527873  0.49468799
   0.27988145]
 [ 1.81783956  1.74857767  1.60404125 ...  1.38670096  1.44381376
   1.30975545]
 ...
 [-0.85069944 -0.76176756 -0.71809672 ... -0.28132609 -0.19389345
  -0.58197686]
 [-1.37340296 -1.25538325 -1.17355853 ... -0.95771871 -1.03135737
  -0.84022321]
 [-1.27515041 -1.18141637 -1.09465963 ... -0.41599249 -0.6095237
  -0.40462695]]


In [13]:
cov_matrix = np.cov(normalized_data, rowvar=False)
print(cov_matrix)

[[1.01176471 1.00765104 0.99620356 ... 0.85723966 0.86113443 0.85076614]
 [1.00765104 1.01176471 1.0062897  ... 0.86869139 0.87127072 0.86087075]
 [0.99620356 1.0062897  1.01176471 ... 0.87801443 0.88055389 0.87140482]
 ...
 [0.85723966 0.86869139 0.87801443 ... 1.01176471 1.00594211 0.99959036]
 [0.86113443 0.87127072 0.88055389 ... 1.00594211 1.01176471 0.99928314]
 [0.85076614 0.86087075 0.87140482 ... 0.99959036 0.99928314 1.01176471]]


In [15]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:, sorted_indices]

In [32]:
print(eigenvalues[:8])

[194.44206269+0.j  11.10481626+0.j   5.97683962+0.j   3.71823387+0.j
   1.03507127+0.j   0.88567495+0.j   0.47217127+0.j   0.28412264+0.j]


In [27]:
print(eigenvectors)

[[-0.06799531+0.j          0.04389992+0.j         -0.07054042+0.j
  ...  0.00197721+0.j         -0.00953719-0.00252574j
  -0.00953719+0.00252574j]
 [-0.06779972+0.j          0.03662822+0.j         -0.08923086+0.j
  ... -0.00625372+0.j          0.03222054+0.0041349j
   0.03222054-0.0041349j ]
 [-0.067078  +0.j          0.02487407+0.j         -0.11060735+0.j
  ...  0.02605387+0.j         -0.02450618-0.01193918j
  -0.02450618+0.01193918j]
 ...
 [-0.06779461+0.j         -0.05752314+0.j         -0.01422555+0.j
  ...  0.00094811+0.j         -0.00865792+0.00703327j
  -0.00865792-0.00703327j]
 [-0.06789229+0.j         -0.05715367+0.j         -0.016254  +0.j
  ... -0.00226231+0.j         -0.00138696+0.0074113j
  -0.00138696-0.0074113j ]
 [-0.06750452+0.j         -0.05307633+0.j         -0.00968719+0.j
  ...  0.01151403+0.j         -0.00083882-0.00054974j
  -0.00083882+0.00054974j]]


In [37]:
top_eigenvectors = eigenvectors[:, :2]
print(top_eigenvectors)

[[-0.06799531+0.j  0.04389992+0.j]
 [-0.06779972+0.j  0.03662822+0.j]
 [-0.067078  +0.j  0.02487407+0.j]
 [-0.0660573 +0.j  0.00789448+0.j]
 [-0.06602205+0.j -0.01014815+0.j]
 [-0.06495949+0.j -0.03542991+0.j]
 [-0.06507628+0.j -0.04941972+0.j]
 [-0.06452911+0.j -0.06075095+0.j]
 [-0.06376794+0.j -0.07226837+0.j]
 [-0.06379797+0.j -0.08366596+0.j]
 [-0.06317534+0.j -0.09889372+0.j]
 [-0.06243769+0.j -0.10781178+0.j]
 [-0.06226063+0.j -0.11070496+0.j]
 [-0.06122418+0.j -0.12058022+0.j]
 [-0.06021168+0.j -0.13028862+0.j]
 [-0.0590558 +0.j -0.13771142+0.j]
 [-0.05760612+0.j -0.14014742+0.j]
 [-0.05639558+0.j -0.14029302+0.j]
 [-0.05588388+0.j -0.14086511+0.j]
 [-0.05563375+0.j -0.14242745+0.j]
 [-0.0553882 +0.j -0.14430204+0.j]
 [-0.0556095 +0.j -0.14588004+0.j]
 [-0.05625332+0.j -0.14515353+0.j]
 [-0.057218  +0.j -0.13889255+0.j]
 [-0.05846701+0.j -0.12583667+0.j]
 [-0.05995857+0.j -0.10450563+0.j]
 [-0.06089911+0.j -0.07276946+0.j]
 [-0.0611038 +0.j -0.0324641 +0.j]
 [-0.05919603+0.j  0

In [38]:

sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:, sorted_indices]

eigenvectors_df = pd.DataFrame(eigenvectors, 
                               columns=[f"PC{i+1}" for i in range(eigenvectors.shape[1])])

print("Eigenvectors Table:")
print(eigenvectors_df)


Eigenvectors Table:
                    PC1                 PC2                 PC3  \
0   -0.067995+0.000000j  0.043900+0.000000j -0.070540+0.000000j   
1   -0.067800+0.000000j  0.036628+0.000000j -0.089231+0.000000j   
2   -0.067078+0.000000j  0.024874+0.000000j -0.110607+0.000000j   
3   -0.066057+0.000000j  0.007894+0.000000j -0.130495+0.000000j   
4   -0.066022+0.000000j -0.010148+0.000000j -0.135379+0.000000j   
..                  ...                 ...                 ...   
211 -0.068455+0.000000j -0.059670+0.000000j -0.008676+0.000000j   
212 -0.068339+0.000000j -0.058621+0.000000j -0.015670+0.000000j   
213 -0.067795+0.000000j -0.057523+0.000000j -0.014226+0.000000j   
214 -0.067892+0.000000j -0.057154+0.000000j -0.016254+0.000000j   
215 -0.067505+0.000000j -0.053076+0.000000j -0.009687+0.000000j   

                    PC4                 PC5                 PC6  \
0   -0.043535+0.000000j  0.090542+0.000000j  0.066224+0.000000j   
1   -0.033431+0.000000j  0.097356+0.00000