In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
from numpy.linalg import eig

def function1(data):
    df1=pd.DataFrame(data)
    correlation_matrix = df1.corr()
    df = pd.DataFrame(data)
    data_centered = df1 - df1.mean()
    cov_matrix = np.cov(data_centered, rowvar=False)
    eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
    eigenvalues = np.real(eigenvalues)
    variance_percentage = (eigenvalues / np.sum(eigenvalues)) * 100
    variance_percentage_df=pd.DataFrame({
        "Feature": feature_names,
        "Explained Variance (%)": variance_percentage
    })
    results_sorted = variance_percentage_df.sort_values(by="Explained Variance (%)", ascending=False)
    results_sorted["Explained Variance (%)"] = results_sorted["Explained Variance (%)"].map("{:.2f}".format)
    print(results_sorted)


In [2]:
file_path ="output_reflectance4.csv"
df = pd.read_csv(file_path, header=0)
feature_names = df.columns[1:] 
data = df.iloc[:9, 1:].values.astype(float)
print("Green Day 1")
function1(data)

Green Day 1
   Feature Explained Variance (%)
0    356.0                  87.55
1    366.0                  10.41
2    376.0                   1.66
3    386.0                   0.16
4    396.0                   0.12
..     ...                    ...
26   616.0                  -0.00
18   536.0                  -0.00
17   526.0                  -0.00
9    446.0                  -0.00
8    436.0                  -0.00

[216 rows x 2 columns]


In [3]:
data = df.iloc[18:25, 1:].values.astype(float)
print("Green Day 2")
print(data)
function1(data)

Green Day 2
[[23.33 19.5  15.22 ...  8.99  8.91  9.2 ]
 [27.86 22.94 18.05 ...  8.84  8.66  9.06]
 [30.18 24.92 19.24 ... 11.73 11.83 12.06]
 ...
 [34.29 29.03 24.59 ... 13.24 13.8  13.59]
 [22.13 17.74 14.05 ...  6.55  6.55  6.8 ]
 [18.59 15.16 11.42 ...  7.08  6.76  6.88]]
   Feature Explained Variance (%)
0    356.0                  92.99
1    366.0                   5.78
2    376.0                   0.79
3    386.0                   0.30
4    396.0                   0.11
..     ...                    ...
7    426.0                  -0.00
24   596.0                  -0.00
25   606.0                  -0.00
11   466.0                  -0.00
6    416.0                  -0.00

[216 rows x 2 columns]


In [4]:
data = df.iloc[34:41, 1:].values.astype(float)
print("Green Day 3")
print(data)
function1(data)

Green Day 3
[[13.65 10.89  8.5  ...  3.22  3.26  2.9 ]
 [23.59 20.86 17.22 ...  8.66  8.68  8.41]
 [22.24 18.7  14.54 ...  7.47  7.43  7.53]
 ...
 [20.54 16.7  13.22 ...  6.27  6.39  5.97]
 [15.47 12.91 10.25 ...  3.69  3.88  3.5 ]
 [11.92  9.88  7.52 ...  2.72  2.57  2.94]]
   Feature Explained Variance (%)
0    356.0                  95.88
1    366.0                   3.53
2    376.0                   0.33
3    386.0                   0.19
4    396.0                   0.05
..     ...                    ...
19   546.0                  -0.00
20   556.0                  -0.00
9    446.0                  -0.00
10   456.0                  -0.00
6    416.0                  -0.00

[216 rows x 2 columns]


In [5]:
data = df.iloc[57:64, 1:].values.astype(float)
print("Green Day 5")
print(data)
function1(data)

Green Day 5
[[21.76 17.84 13.81 ...  7.1   6.38  5.66]
 [36.82 32.07 27.48 ... 17.48 16.79 16.66]
 [38.35 33.24 27.92 ... 12.16 13.02 12.21]
 ...
 [29.38 25.61 21.1  ... 11.53 12.05 10.85]
 [14.92 12.88 10.33 ...  3.84  4.19  3.99]
 [15.67 12.92  9.47 ...  1.96  2.17  2.16]]
   Feature Explained Variance (%)
0    356.0                  97.24
1    366.0                   2.14
2    376.0                   0.34
3    386.0                   0.14
4    396.0                   0.09
..     ...                    ...
24   596.0                  -0.00
25   606.0                  -0.00
12   476.0                  -0.00
7    426.0                  -0.00
6    416.0                  -0.00

[216 rows x 2 columns]


In [6]:
data = df.iloc[72:78, 1:].values.astype(float)
print("Green Day 6")
print(data)
function1(data)

Green Day 6
[[15.05 13.27 11.41 ...  3.44  3.42  3.47]
 [18.04 15.84 13.66 ...  3.54  4.12  3.12]
 [10.88  8.7   6.39 ...  1.52  1.54  0.93]
 [14.08 11.77  9.41 ...  2.88  2.42  2.4 ]
 [10.73  8.91  6.99 ...  1.09  1.46  1.87]
 [11.91 10.08  7.56 ...  2.76  3.12  1.4 ]]
   Feature Explained Variance (%)
0    356.0                  92.56
1    366.0                   4.27
2    376.0                   2.83
3    386.0                   0.28
4    396.0                   0.06
..     ...                    ...
17   526.0                  -0.00
16   516.0                  -0.00
28   636.0                  -0.00
11   466.0                  -0.00
5    406.0                  -0.00

[216 rows x 2 columns]


In [7]:
data = df.iloc[9:18, 1:].values.astype(float)
print("Red Day 1")
print(data)
function1(data)

Red Day 1
[[14.84 12.07  9.48 ...  3.47  3.45  3.57]
 [22.33 18.67 14.43 ...  5.34  5.21  4.6 ]
 [ 6.92  5.49  3.96 ...  0.86  0.67  1.01]
 ...
 [23.1  18.52 13.96 ...  3.15  2.81  3.3 ]
 [14.1  11.04  8.74 ...  1.68  1.96  2.16]
 [12.82  9.87  7.26 ...  1.49  1.81  1.23]]
   Feature Explained Variance (%)
0    356.0                  97.77
1    366.0                   1.67
2    376.0                   0.45
3    386.0                   0.06
4    396.0                   0.03
..     ...                    ...
8    436.0                  -0.00
18   536.0                  -0.00
17   526.0                  -0.00
12   476.0                  -0.00
13   486.0                  -0.00

[216 rows x 2 columns]


In [8]:
data = df.iloc[25:34, 1:].values.astype(float)
print("Red Day 2")
print(data)
function1(data)

Red Day 2
[[12.03  9.45  6.99 ...  3.66  3.79  3.75]
 [17.83 14.43 11.29 ...  5.01  4.99  4.17]
 [17.87 14.45 10.82 ...  6.49  6.72  6.44]
 ...
 [14.1  11.04  8.74 ...  1.68  1.96  2.16]
 [29.31 24.28 18.82 ...  5.98  6.05  5.74]
 [10.02  8.23  6.42 ...  1.87  1.83  2.04]]
   Feature Explained Variance (%)
0    356.0                  98.29
1    366.0                   1.21
2    376.0                   0.31
3    386.0                   0.10
4    396.0                   0.06
..     ...                    ...
18   536.0                  -0.00
15   506.0                  -0.00
11   466.0                  -0.00
12   476.0                  -0.00
13   486.0                  -0.00

[216 rows x 2 columns]


In [9]:
data = df.iloc[41:49, 1:].values.astype(float)
print("Red Day 3")
print(data)
function1(data)

Red Day 3
[[21.09 17.43 14.03 ...  5.42  5.35  5.53]
 [30.13 25.92 21.62 ...  7.79  7.82  7.47]
 [22.66 18.9  14.8  ...  4.49  4.89  4.08]
 ...
 [25.92 21.89 18.35 ...  6.14  6.1   6.38]
 [20.17 16.72 12.45 ...  5.24  5.53  4.94]
 [11.01  8.75  6.67 ...  1.96  1.82  1.59]]
   Feature Explained Variance (%)
0    356.0                  97.22
1    366.0                   1.74
2    376.0                   0.54
3    386.0                   0.34
4    396.0                   0.14
..     ...                    ...
28   636.0                  -0.00
25   606.0                  -0.00
14   496.0                  -0.00
9    446.0                  -0.00
10   456.0                  -0.00

[216 rows x 2 columns]


In [10]:
data = df.iloc[49:57, 1:].values.astype(float)
print("Red Day 4")
print(data)
function1(data)

Red Day 4
[[26.85 21.05 16.68 ...  7.16  6.88  6.7 ]
 [32.65 27.7  23.   ... 10.34 10.21 11.36]
 [21.3  16.24 12.05 ...  3.53  4.3   4.4 ]
 ...
 [18.64 14.3  10.42 ...  1.31  1.52  1.27]
 [15.18 12.33  8.95 ...  2.52  2.4   1.37]
 [20.29 17.22 13.17 ...  3.33  3.44  3.74]]
   Feature Explained Variance (%)
0    356.0                  89.78
1    366.0                   7.54
2    376.0                   1.63
3    386.0                   0.69
4    396.0                   0.28
..     ...                    ...
25   606.0                  -0.00
24   596.0                  -0.00
7    426.0                  -0.00
8    436.0                  -0.00
9    446.0                  -0.00

[216 rows x 2 columns]


In [11]:
data = df.iloc[64:72, 1:].values.astype(float)
print("Red Day 5")
print(data)
function1(data)

Red Day 5
[[22.27 18.36 13.6  ...  6.42  6.33  6.5 ]
 [32.34 27.99 22.84 ...  9.77  9.69  9.69]
 [26.95 23.55 18.69 ...  6.71  5.81  6.08]
 ...
 [23.46 19.15 15.21 ...  6.6   6.58  5.46]
 [13.69 11.3   9.1  ...  3.65  4.01  4.36]
 [19.72 16.69 13.86 ...  5.02  4.64  3.82]]
   Feature Explained Variance (%)
0    356.0                  91.42
1    366.0                   5.38
2    376.0                   1.82
3    386.0                   0.97
4    396.0                   0.32
..     ...                    ...
21   566.0                  -0.00
22   576.0                  -0.00
12   476.0                  -0.00
13   486.0                  -0.00
14   496.0                  -0.00

[216 rows x 2 columns]


In [12]:
data = df.iloc[78:86, 1:].values.astype(float)
print("Red Day 6")
print(data)
function1(data)

Red Day 6
[[12.35 10.03  7.94 ...  3.44  3.43  2.93]
 [11.2   8.97  7.27 ...  3.1   2.52  2.59]
 [ 8.37  6.78  4.88 ...  1.18  1.33  0.88]
 ...
 [14.46 12.38  9.81 ...  4.78  5.12  3.63]
 [10.47  9.11  7.27 ...  2.57  2.42  2.8 ]
 [11.22  9.6   7.71 ...  4.34  3.78  4.2 ]]
   Feature Explained Variance (%)
0    356.0                  81.19
1    366.0                  14.49
2    376.0                   3.36
3    386.0                   0.51
4    396.0                   0.28
..     ...                    ...
11   466.0                  -0.00
13   486.0                  -0.00
14   496.0                  -0.00
15   506.0                  -0.00
16   516.0                  -0.00

[216 rows x 2 columns]


In [20]:

data = [[20, 30, 22, 60, 70, 62, 50]]
df = pd.DataFrame(data, columns=['A', 'B', 'C', 'D', 'E', 'F', 'G'])
cov_matrix = np.cov(df, rowvar=False)
print(cov_matrix)

423.80952380952385
