In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
from numpy.linalg import eig
file_path ="output_reflectance4.csv"

df = pd.read_csv(file_path, header=0)

feature_names = df.columns[1:] 
data = df.iloc[18:25, 1:].values.astype(float)
print(data.shape)
df1=pd.DataFrame(data)

(7, 216)


In [2]:
correlation_matrix = df1.corr()
print(correlation_matrix)

          0         1         2         3         4         5         6    \
0    1.000000  0.995089  0.985147  0.961788  0.947429  0.949548  0.951534   
1    0.995089  1.000000  0.992426  0.975420  0.959915  0.961318  0.963059   
2    0.985147  0.992426  1.000000  0.992307  0.982649  0.982998  0.983829   
3    0.961788  0.975420  0.992307  1.000000  0.996999  0.996688  0.996460   
4    0.947429  0.959915  0.982649  0.996999  1.000000  0.999597  0.999283   
..        ...       ...       ...       ...       ...       ...       ...   
211  0.933126  0.923093  0.915666  0.893301  0.876976  0.886827  0.886012   
212  0.918996  0.911255  0.896690  0.873052  0.853778  0.864897  0.864307   
213  0.905217  0.896567  0.884625  0.858798  0.838517  0.850051  0.849255   
214  0.914767  0.907483  0.900878  0.875914  0.855962  0.866296  0.865271   
215  0.935865  0.935477  0.922236  0.895485  0.871099  0.880163  0.880002   

          7         8         9    ...       206       207       208  \
0  

In [3]:
df = pd.DataFrame(data)

data_centered = df1 - df1.mean()

cov_matrix = np.cov(data_centered, rowvar=False)

print(cov_matrix)

[[28.22019524 24.51674286 22.0956119  ... 12.22760238 13.46198333
  12.79669048]
 [24.51674286 21.51008095 19.43319286 ... 10.57334524 11.65945
  11.16756905]
 [22.0956119  19.43319286 17.82582857 ...  9.49713571 10.53681667
  10.02239048]
 ...
 [12.22760238 10.57334524  9.49713571 ...  6.46572381  7.03103333
   6.48707143]
 [13.46198333 11.65945    10.53681667 ...  7.03103333  7.67426667
   7.08196667]
 [12.79669048 11.16756905 10.02239048 ...  6.48707143  7.08196667
   6.62534762]]


In [4]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print(eigenvalues.shape)
print(eigenvectors.shape)

(216,)
(216, 216)


In [5]:
band_variances = np.diag(cov_matrix)
print(band_variances.size)
print(band_variances)

216
[ 28.22019524  21.51008095  17.82582857  16.21294762  18.0505619
  17.78202381  17.86836667  16.96219524  16.76581429  19.67609524
  25.31188095  27.98281429  30.53326667  33.02256667  44.64594762
  69.00044762  99.68952857 127.68329524 147.9429     161.68325714
 160.23224762 162.11272381 162.44105714 158.91101429 153.51145714
 145.42713333 135.52339524 130.3992     114.05298095 110.33333333
  95.71359048  54.27024762  41.24419048  69.34948095 167.68594762
 203.22578095 186.43934762 161.09974762 146.10639524 147.80475714
 138.37719048 147.10192381 149.01342381 152.99784762 136.76542857
 133.1168619  132.89311429 129.3293619  131.94018095 139.9984619
 136.24698095 136.99925714 136.11291429 129.28744762 124.69652857
 123.20619524 122.16631429 121.63799524 121.05663333 124.75079048
 124.49985714 127.43845714 130.9366619  104.2218     101.50029524
  99.9507619  100.9854619   99.84532381  98.6255619   98.98398095
  99.85329048  99.98369048 100.13745714  99.9687      99.76076667
 100.294

In [6]:
eigenvectors=np.real(eigenvectors)
eigenvalues=np.real(eigenvalues)
factor_loadings = np.zeros_like(eigenvectors)
for k in range(eigenvectors.shape[0]): 
    for p in range(eigenvectors.shape[1]): 
        factor_loadings[k, p] = (eigenvectors[k, p] * np.sqrt(eigenvalues[p])) / np.sqrt(band_variances[k])


C:\Users\sumat\AppData\Local\Temp\ipykernel_6340\3098104741.py:6: RuntimeWarning: invalid value encountered in sqrt
  factor_loadings[k, p] = (eigenvectors[k, p] * np.sqrt(eigenvalues[p])) / np.sqrt(band_variances[k])


In [7]:
first_4_factor_loadings = factor_loadings[:, :4]

print( first_4_factor_loadings)

[[-9.82761072e-01  1.56366064e-01 -7.83354555e-03  6.15780595e-02]
 [-9.64851606e-01  2.12793096e-01 -1.50601799e-02  1.04422485e-01]
 [-9.38282728e-01  2.70403861e-01  2.58738885e-02  1.48698232e-01]
 [-9.01342624e-01  3.42187710e-01  1.14184776e-01  1.62007658e-01]
 [-8.82616570e-01  3.80190684e-01  1.63843623e-01  1.43956759e-01]
 [-8.87313766e-01  3.70851839e-01  1.70261872e-01  1.55845457e-01]
 [-8.89521790e-01  3.77019832e-01  1.58775557e-01  1.51606513e-01]
 [-9.00672622e-01  3.58864963e-01  1.44595908e-01  1.42610307e-01]
 [-8.98748155e-01  3.54778437e-01  1.51158032e-01  1.52024277e-01]
 [-9.00573524e-01  3.70978083e-01  1.48707048e-01  1.15742160e-01]
 [-8.99756020e-01  3.90951979e-01  1.43604807e-01  8.48081860e-02]
 [-8.96061995e-01  4.02965596e-01  1.47376238e-01  7.52376728e-02]
 [-8.98298905e-01  4.05087084e-01  1.38948243e-01  6.47912614e-02]
 [-8.90995497e-01  4.19940883e-01  1.49312255e-01  5.23466898e-02]
 [-8.89586010e-01  4.31084258e-01  1.40234833e-01  2.78399248e

In [8]:
variance_percentage = (eigenvalues / np.sum(eigenvalues)) * 100
print(variance_percentage)

[ 9.29903687e+01  5.77621894e+00  7.92232989e-01  3.02277179e-01
  1.08362032e-01  3.05401474e-02 -3.23006637e-15 -1.98531729e-15
 -1.98531729e-15  3.42918613e-15  3.42918613e-15 -2.73372401e-15
 -8.70982300e-16 -8.70982300e-16  2.98902496e-15  2.03506094e-15
  2.03506094e-15  7.46056412e-16  7.46056412e-16 -1.80231039e-15
 -1.80231039e-15  2.20791985e-15  2.20791985e-15  2.38190186e-15
 -2.17450262e-15 -2.17450262e-15 -8.64598209e-16 -8.64598209e-16
  1.60456239e-15  1.60456239e-15  6.31548718e-16  6.31548718e-16
 -1.64167870e-15 -1.64167870e-15 -4.85093340e-16 -4.85093340e-16
  1.59307324e-15  1.59307324e-15 -1.18311851e-15 -1.18311851e-15
 -1.53167093e-15 -1.53167093e-15  3.94185682e-16  3.94185682e-16
 -1.31089521e-15 -1.31089521e-15  1.57045239e-15  1.52347429e-15
  1.52347429e-15  9.01789438e-16  9.01789438e-16  1.26718436e-15
  1.26718436e-15  1.14013104e-15  1.14013104e-15  1.16542008e-15
  1.16542008e-15 -5.97165919e-16 -5.97165919e-16 -1.08489864e-15
 -1.08489864e-15 -1.20786

In [9]:
formatted_data = np.round(variance_percentage, 3)
print(formatted_data)

[ 9.299e+01  5.776e+00  7.920e-01  3.020e-01  1.080e-01  3.100e-02
 -0.000e+00 -0.000e+00 -0.000e+00  0.000e+00  0.000e+00 -0.000e+00
 -0.000e+00 -0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00
  0.000e+00 -0.000e+00 -0.000e+00  0.000e+00  0.000e+00  0.000e+00
 -0.000e+00 -0.000e+00 -0.000e+00 -0.000e+00  0.000e+00  0.000e+00
  0.000e+00  0.000e+00 -0.000e+00 -0.000e+00 -0.000e+00 -0.000e+00
  0.000e+00  0.000e+00 -0.000e+00 -0.000e+00 -0.000e+00 -0.000e+00
  0.000e+00  0.000e+00 -0.000e+00 -0.000e+00  0.000e+00  0.000e+00
  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00
  0.000e+00  0.000e+00  0.000e+00 -0.000e+00 -0.000e+00 -0.000e+00
 -0.000e+00 -0.000e+00 -0.000e+00  0.000e+00  0.000e+00 -0.000e+00
 -0.000e+00  0.000e+00  0.000e+00 -0.000e+00 -0.000e+00  0.000e+00
  0.000e+00 -0.000e+00 -0.000e+00 -0.000e+00 -0.000e+00  0.000e+00
  0.000e+00 -0.000e+00 -0.000e+00  0.000e+00  0.000e+00  0.000e+00
  0.000e+00 -0.000e+00 -0.000e+00  0.000e+00  0.000e+00  0.000

In [10]:
idx = eigenvalues.argsort()[::-1]

# Sort the eigenvalues in descending order 
eigenvalues = eigenvalues[idx]

# sort the corresponding eigenvectors accordingly
eigenvectors = eigenvectors[:,idx]

In [11]:
explained_var = np.cumsum(eigenvalues) / np.sum(eigenvalues)
explained_var

array([0.92990369, 0.98766588, 0.99558821, 0.99861098, 0.9996946 ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

In [13]:
n_components = np.argmax(explained_var >= 0.99) + 1
n_components

np.int64(3)